title: India Blogs
author: Ranjanunicoder
email: Ranjanamp6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  India Blogs is a platform for EveryOne to share there knowledge about the future technologies and there efficient implements in all aspects.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
